import { toPng } from 'html-to-image';
import type { MindMap, MindMapNode } from '../types/mindmap';

function nodeToMarkdown(node: MindMapNode, depth: number = 0): string {
  const indent = '  '.repeat(depth);
  const prefix = depth === 0 ? '# ' : depth === 1 ? '## ' : `${indent}- `;
  const speakerTag = node.speaker ? ` _(${node.speaker})_` : '';
  const typeTag = node.type !== 'topic' && node.type !== 'point' ? ` [${node.type}]` : '';

  let md = `${prefix}${node.label}${speakerTag}${typeTag}\n`;

  for (const child of node.children) {
    md += nodeToMarkdown(child, depth + 1);
  }

  return md;
}

export function exportToMarkdown(mindMap: MindMap): string {
  let md = nodeToMarkdown(mindMap.root);

  if (mindMap.crossReferences.length > 0) {
    md += '\n---\n\n### Cross-References\n\n';
    for (const ref of mindMap.crossReferences) {
      md += `- ${ref.sourceId} → ${ref.targetId} (${ref.relationship})\n`;
    }
  }

  md += `\n---\n_Generated by MindFlow | ${mindMap.metadata.lastUpdated}_\n`;
  return md;
}

export function exportToJSON(mindMap: MindMap): string {
  return JSON.stringify(mindMap, null, 2);
}

function nodeToOPML(node: MindMapNode, indent: number = 2): string {
  const pad = ' '.repeat(indent);
  const attrs = `text="${escapeXml(node.label)}" _type="${node.type}"${
    node.speaker ? ` _speaker="${escapeXml(node.speaker)}"` : ''
  }`;

  if (node.children.length === 0) {
    return `${pad}<outline ${attrs}/>\n`;
  }

  let xml = `${pad}<outline ${attrs}>\n`;
  for (const child of node.children) {
    xml += nodeToOPML(child, indent + 2);
  }
  xml += `${pad}</outline>\n`;
  return xml;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function exportToOPML(mindMap: MindMap): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
  <head>
    <title>${escapeXml(mindMap.root.label)}</title>
    <dateCreated>${mindMap.metadata.lastUpdated}</dateCreated>
  </head>
  <body>
${nodeToOPML(mindMap.root)}  </body>
</opml>`;
}

export async function exportToPNG(elementId: string): Promise<Blob> {
  const element = document.getElementById(elementId);
  if (!element) throw new Error('Mind map element not found');

  const dataUrl = await toPng(element, {
    backgroundColor: '#0a0a16',
    pixelRatio: 2,
    filter: (node: HTMLElement) => {
      // Exclude UI controls from the screenshot
      return !node.classList?.contains('mindflow-controls');
    },
  });

  const response = await fetch(dataUrl);
  return response.blob();
}

export function downloadFile(content: string | Blob, filename: string, mimeType?: string): void {
  const blob =
    content instanceof Blob
      ? content
      : new Blob([content], { type: mimeType || 'text/plain;charset=utf-8' });

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
